Pandas-DataFrame and series

pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and dataframe. A series is a one -dimensional array-like object, while a dataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes(rows and columns).

In [1]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\TANUSHREE\miniconda3\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\TANUSHREE\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\TANUSHREE\miniconda3\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\Users\TANUSHREE\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 456.0 kB/s eta 0:00:21
   -- ------------------------------------- 0.5/9.7 MB 456.0 kB/s eta 0:00:21
   -- ------------------------------------- 0.5/9.7 MB 456.0 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.7 MB 435.1 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.7 MB 435.1 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.7 MB 435.1 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.7 MB 424.6 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.7 MB 424.6 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.7 MB 424.6 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.7 MB 442.3 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.7 MB 442.3 kB/s eta 0:00:20
   ------ --------------------------------- 1.6/9.7 MB 457.7 kB/s eta 0:00:18
   ------ --------------------------------- 1.6/9.7 MB 457.7 kB/s eta 0:00:18
   ------- -------------------------------- 1.8/9.7 MB 476.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.7 MB 476.2 kB/s eta 0:00:17
   -------- ------------------------------- 2.1/9.7 MB 496.8 kB/s eta 0:00:16
   -------- ------------------------------- 2.1/9.7 MB 496.8 kB/s eta 0:00:16
   --------- ------------------------------ 2.4/9.7 MB 508.1 kB/s eta 0:00:15
   --------- ------------------------------ 2.4/9.7 MB 508.1 kB/s eta 0:00:15
   ---------- ----------------------------- 2.6/9.7 MB 516.2 kB/s eta 0:00:14
   ---------- ----------------------------- 2.6/9.7 MB 516.2 kB/s eta 0:00:14
   ---------- ----------------------------- 2.6/9.7 MB 516.2 kB/s eta 0:00:14
   ----------- ---------------------------- 2.9/9.7 MB 513.8 kB/s eta 0:00:14
   ----------- ---------------------------- 2.9/9.7 MB 513.8 kB/s eta 0:00:14
   ------------ --------------------------- 3.1/9.7 MB 520.4 kB/s eta 0:00:13
   ------------ --------------------------- 3.1/9.7 MB 520.4 kB/s eta 0:00:13
   ------------ --------------------------- 3.1/9.7 MB 520.4 kB/s eta 0:00:13
   ------------ --------------------------- 3.1/9.7 MB 520.4 kB/s eta 0:00:13
   ------------- -------------------------- 3.4/9.7 MB 500.1 kB/s eta 0:00:13
   ------------- -------------------------- 3.4/9.7 MB 500.1 kB/s eta 0:00:13
   ------------- -------------------------- 3.4/9.7 MB 500.1 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.7 MB 487.6 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.7 MB 487.6 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.7 MB 487.6 kB/s eta 0:00:13
   ---------------- ----------------------- 3.9/9.7 MB 487.6 kB/s eta 0:00:12
   ---------------- ----------------------- 3.9/9.7 MB 487.6 kB/s eta 0:00:12
   ----------------- ---------------------- 4.2/9.7 MB 492.4 kB/s eta 0:00:12
   ----------------- ---------------------- 4.2/9.7 MB 492.4 kB/s eta 0:00:12
   ----------------- ---------------------- 4.2/9.7 MB 492.4 kB/s eta 0:00:12
   ------------------ --------------------- 4.5/9.7 MB 491.2 kB/s eta 0:00:11
   ------------------ --------------------- 4.5/9.7 MB 491.2 kB/s eta 0:00:11
   ------------------ --------------------- 4.5/9.7 MB 491.2 kB/s eta 0:00:11
   ------------------- -------------------- 4.7/9.7 MB 486.6 kB/s eta 0:00:11
   ------------------- -------------------- 4.7/9.7 MB 486.6 kB/s eta 0:00:11
   ------------------- -------------------- 4.7/9.7 MB 486.6 kB/s eta 0:00:11
   -------------------- ------------------- 5.0/9.7 MB 477.4 kB/s eta 0:00:10
   -------------------- ------------------- 5.0/9.7 MB 477.4 kB/s eta 0:00:10
   -------------------- ------------------- 5.0/9.7 MB 477.4 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 471.9 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 471.9 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 471.9 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 471.9 kB/s eta 0:00:10
   --------------------- ------------------ 5.2/9.7 MB 471.9 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.7 MB 456.5 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.7 MB 456.5 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.7 MB 456.5 kB/s eta 0:00:10
   ----------------------- ---------------- 5.8/9.7 MB 454.6 kB/s eta 0:00:09
   ----------------------- ---------------- 5.8/9.7 MB 454.6 kB/s eta 0:00:09
   ----------------------- ---------------- 5.8/9.7 MB 454.6 kB/s eta 0:00:09
   ------------------------ --------------- 6.0/9.7 MB 453.6 kB/s eta 0:00:09
   ------------------------ --------------- 6.0/9.7 MB 453.6 kB/s eta 0:00:09
   ------------------------ --------------- 6.0/9.7 MB 453.6 kB/s eta 0:00:09
   ------------------------- -------------- 6.3/9.7 MB 449.1 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 449.1 kB/s eta 0:00:08
   ------------------------- -------------- 6.3/9.7 MB 449.1 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 450.3 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 450.3 kB/s eta 0:00:08
   -------------------------- ------------- 6.6/9.7 MB 450.3 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 448.9 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 448.9 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 448.9 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.7 MB 446.8 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.7 MB 446.8 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.7 MB 446.8 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 445.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 445.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 445.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 445.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 445.2 kB/s eta 0:00:06
   ------------------------------- -------- 7.6/9.7 MB 432.5 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.7 MB 432.5 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.7 MB 432.5 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.7 MB 432.5 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.7 MB 432.5 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 424.1 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 424.1 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 424.1 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.7 MB 421.5 kB/s eta 0:00:04
   --------------------------------- ------ 8.1/9.7 MB 421.5 kB/s eta 0:00:04
   --------------------------------- ------ 8.1/9.7 MB 421.5 kB/s eta 0:00:04
   --------------------------------- ------ 8.1/9.7 MB 421.5 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 417.8 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 417.8 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 417.8 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.7 MB 417.1 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 417.1 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 417.1 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.7 MB 418.0 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 418.0 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 418.0 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 418.0 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 416.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 416.3 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.7 MB 418.1 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 418.1 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 418.1 kB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 420.8 kB/s  0:00:23
Installing collected packages: pandas
Successfully installed pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [6]:
## series 
#3 A pandas series is a one-dimenctional array-like object that can hold any data type. It is similar a column in a table.

import pandas as pd
data =[1,2,3,4,5]
series=pd.Series(data)
print("series \n",series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [7]:
## create a series from dictionary 

data={'a':1,'b':2, 'c':3}
series_data=pd.Series(data)
print(series_data)

a    1
b    2
c    3
dtype: int64

In [8]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [10]:
## DataFrame -> 2-dimenctional mutable and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It is similar to a spreadsheet or SQL table.
## create a DatFrame from a dictionary of list

data={
    'Nmae':['Tanu','Bhanu','Sanju'],
    'Age':[21,19,23],
    'City':['Bangalore','Shimoga','Mysore']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Nmae  Age       City
0   Tanu   21  Bangalore
1  Bhanu   19    Shimoga
2  Sanju   23     Mysore
<class 'pandas.DataFrame'>

In [31]:
## Create a Dtaa Frame from a list of Dictionaries

data=[
    {'Name':'Tanu','Age':21,'City':'Bangalore'},
    {'Name':'Bhanu','Age':19,'City':'Shimoga'},
    {'Name':'Sanju','Age':23,'City':'Mysore'}

]
df=pd.DataFrame(data)
print(df)

    Name  Age       City
0   Tanu   21  Bangalore
1  Bhanu   19    Shimoga
2  Sanju   23     Mysore

In [15]:
pd.read_csv('example.csv')
df.head(1)

FileNotFoundError: [Errno 2] No such file or directory: 'example.csv'

In [17]:
## Accessing data from DataFrame

df

    Nmae  Age       City
0   Tanu   21  Bangalore
1  Bhanu   19    Shimoga
2  Sanju   23     Mysore

In [21]:
df['Name']

0     Tanu
1    Bhanu
2    Sanju
Name: Name, dtype: str

In [ ]:
## loc-> row index
df.loc[0]

Name         Tanu
Age            21
City    Bangalore
Name: 0, dtype: object

In [23]:
## iloc-> column index
df.iloc[0]

Name         Tanu
Age            21
City    Bangalore
Name: 0, dtype: object

In [33]:
## Accessing specified element

df.at[2,'Age']

np.int64(23)

In [34]:
df.at[2,'Name']

'Sanju'

In [35]:
## Accessing a specified element usig iat

df.iat[2,0]

'Sanju'

In [36]:
## Data manupulation with DataFrame
df

    Name  Age       City
0   Tanu   21  Bangalore
1  Bhanu   19    Shimoga
2  Sanju   23     Mysore

In [37]:
df['Salary']=[50000,60000,55000]
df

    Name  Age       City  Salary
0   Tanu   21  Bangalore   50000
1  Bhanu   19    Shimoga   60000
2  Sanju   23     Mysore   55000

In [41]:
## Remove a column

df.drop('Salary',axis=1,inplace=True)

In [42]:
df

    Name  Age       City
0   Tanu   21  Bangalore
1  Bhanu   19    Shimoga
2  Sanju   23     Mysore

In [45]:
#3 Add age to the column

df['Age']=df['Age']+2

In [46]:
df

    Name  Age       City
0   Tanu   24  Bangalore
1  Bhanu   22    Shimoga
2  Sanju   26     Mysore

In [47]:
df.drop(0)

    Name  Age     City
1  Bhanu   22  Shimoga
2  Sanju   26   Mysore

In [48]:
df.drop(0,inplace=True)

In [49]:
df

    Name  Age     City
1  Bhanu   22  Shimoga
2  Sanju   26   Mysore

In [ ]:
df=pd.read_csv('sales_data.csv')
df.head()